spring:
  application:
    name: USER-SERVICE
  data:
    mongodb:
      uri: mongodb://admin:admin%4012345@mongdo-server:27017
      database: user_db
server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
      initialInstanceInfoReplicationIntervalSeconds: 5
      registryFetchIntervalSeconds: 5
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5
